### ISSUE TITLE
To-do for release 0.4.2

### ISSUE THREAD

**Issue by csyhuang** [csyhuang/hn2016_falwa#37]
- [x] Incorporate changes made by Christopher - Include instructions on how to remove old compiled fortran modules
- [x] Remove `download_data.py` as ERA-I has deprecated
- [x] Check if codecov is working (seems it stopped working)
- [x] Check consistency between `readme.md` and documentation
- [x] Add additional unit tests for oopinterface (sanity checks)
- [x] Clean up sample scripts (in folder `examples/`)
- (to be updated)
