### ISSUE TITLE
To-do items for Release 1.0

### ISSUE THREAD

**Issue by csyhuang** [csyhuang/hn2016_falwa#75]
Update: The new version (v1.0) will be released by Nov 1, 2023 tentatively. We plan to change the python package name from `hn2016_falwa` to `falwa`.

Update [2023/11/5]: For testing the MDTF integration, I will deploy a pre-release version `1.0.0a0` from the branch `pre-release-1.0.0a0` with the following enhancement/fixes:

- [x] Python package name change from `hn2016_falwa` to `falwa` #91
- [x] QGDataset does not support data input with even number of latitude gridpoints #85
- [x] Use Cartopy instead of Basemap (deprecated) in all the visualization examples #87
- [x] Bug in GitHub action #82
- [x] Code fix for zonal advective flux computation #92 

Update [2023/11/5]: The rest of the issues will be addressed in upcoming release(s):

- Solve Memory Issues of QGField #50
- Use `pyproject.toml` for setup #73 
    - Reference: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
- Provide default variable encoding parameters for xarray's to_netcdf #72 
- Generalize hemisphere_to_global to be used for both numpy and xarray interface #48
(to be cont.)

Incremental changes will first be merged to branch `release1.0`. On the release date, branch `release1.0` will be merged to `master`.

**Comment by csyhuang** [comment]
@chpolste Just a heads up: to test the MDTF PR, (and while I haven't heard from Noboru yet) I will deploy a pre-release version `1.0.0a0`, hopefully working on test.pypi, or if not, on pypi.

[Indexing notation](https://peps.python.org/pep-0440/#pre-releases)

**Comment by chpolste** [comment]
👍

I'm afraid the dask integration will have to wait for another release. I have set aside some time for the paper (if necessary), but it's too busy at the moment to engage with a side project as #50, unfortunately.

**Comment by csyhuang** [comment]
@chpolste Thanks for the update! Indeed the adjustment you have made in `QGDataset` is already super helpful and helped solve a bottleneck in the MDTF task (now it is running in reasonable time). I updated the issue ticket above to reflect what will be included in this release. Let's have the dask integration in upcoming release instead.

Given tomorrow is the MDTF monthly meeting, I wish to test submission today such that I can raise issues to the team tomorrow. Hopefully I can wrap up the paper in a day or two. I'll get in touch via email. Thank you for setting time aside for the paper 🙏

**Comment by csyhuang** [comment]
To rename package on PyPI index, see: https://github.com/simonw/pypi-rename
